belfast/groupsheets/urls.py
from django.conf.urls import patterns, include, url
from belfast.groupsheets import views

urlpatterns = patterns(
    '',
    url(r'^$', views.list_groupsheets, name='list'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<id>[a-z0-9_-]+)/$', views.view_sheet, name='view'),
    url(r'^xml/(?P<name>[-a-z0-9_.]+)/$', views.teixml, name='xml'),
)

belfast/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib.sitemaps import FlatPageSitemap

from belfast.pages import views as pages_views
from belfast.sitemaps import OtherViewsSitemap
from belfast.groupsheets.sitemaps import GroupSheetsSitemap, XmlDocumentsSitemap
from belfast.people.sitemaps import ProfileSitemap

# enable django db-admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', pages_views.site_index, name='site-index'),
    url(r'^groupsheets/', include('belfast.groupsheets.urls',
        namespace='groupsheets')),
    url(r'^people/', include('belfast.people.urls',
        namespace='people')),
    url(r'^network/', include('belfast.network.urls',
        namespace='network')),
    url(r'^', include('belfast.pages.urls')),
    # add redirect for favicon at root of site
    (r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True)),
    # Examples:
    # url(r'^$', 'belfast.views.home', name='home'),
    # url(r'^belfast/', include('belfast.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),


    # belfast group rdf ontology
    #   http://belfastgroup.library.emory.edu/ontologies/2013/6/belfastgroup/
    url(r'^ontologies/2013/6/belfastgroup/$',
        TemplateView.as_view(template_name='bg-ontology.xml',
        content_type='text/xml'), name='bg-ontology'),
    url(r'^robots\.txt$',
        TemplateView.as_view(template_name='robots.txt',
        content_type='text/plain'), name='robots.txt'),
)

# xml sitemaps for search-engine discovery
sitemaps = {
    'groupsheets': GroupSheetsSitemap,
    'xmlgroupsheets': XmlDocumentsSitemap,
    'profiles': ProfileSitemap,
    'flatpages': FlatPageSitemap,
    'other': OtherViewsSitemap
}

urlpatterns += patterns('django.contrib.sitemaps.views',
    (r'^sitemap\.xml$', 'index', {'sitemaps': sitemaps}),
    (r'^sitemap-(?P<section>.+)\.xml$', 'sitemap', {'sitemaps': sitemaps}),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

belfast/groupsheets/models.py
# no db models for this app

belfast/groupsheets/forms.py
from django import forms
from django.utils.safestring import mark_safe
from eulcommon.searchutil import search_terms


class KeywordSearchForm(forms.Form):
    "Simple keyword search form"
    kw_help = '''enter one or more terms;
    use * or ? for wildcards, quotes for an "exact phrase"'''
    keywords = forms.CharField(
        help_text=kw_help,
        widget=forms.TextInput(attrs={
            'class': 'searchform',
            'placeholder': 'Search digital editions...',
            'autocomplete': 'off',
            'data-toggle': 'tooltip',
            'data-placement': 'bottom',
            'data-original-title': kw_help
        }),
        error_messages={'required': 'No search terms were entered.'}
    )

    def clean_keywords(self):
        data = self.cleaned_data['keywords']
        # doesn't care about mis-matched quotes, just strips them out
        terms = search_terms(data)
        for t in terms:
            if t.startswith('*') or t.startswith('?'):
                raise forms.ValidationError(
                    mark_safe('Search terms may not begin with wildcards <b>*</b> or <b>?</b>'),
                    code='invalid')
        # NOTE: this cleans up mismatched quotes and converts them to terms
        data = ' '.join('"%s"' % t if ' ' in t else t for t in terms)
        return data

belfast/groupsheets/views.py
from collections import defaultdict
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import Http404, HttpResponse
from django.views.decorators.http import last_modified

from eulexistdb.exceptions import DoesNotExist, ExistDBException
import logging
import urllib

from belfast import rdfns
from belfast.groupsheets.forms import KeywordSearchForm
from belfast.groupsheets.rdfmodels import TeiGroupSheet, TeiDocument, \
    get_rdf_groupsheets, groupsheet_by_url
from belfast.util import rdf_data_lastmodified, network_data_lastmodified, \
    local_uri, get_flatpage

logger = logging.getLogger(__name__)


def rdf_lastmod(request, *args, **kwargs):
    '''Helper method to return RDF last-modified information, for use with
    :meth:`django.views.decorators.http.last_modified`'''
    return rdf_data_lastmodified()


def rdf_nx_lastmod(request, *args, **kwargs):
    '''Helper method to most recent of RDF *or* Network graph files last-modified
    information, for use with :meth:`django.views.decorators.http.last_modifie`'''
    return max(rdf_data_lastmodified(), network_data_lastmodified())

# TODO: add etag/last-modified headers for views based on single-document TEI
# use document last-modification date in eXist (should be similar to findingaids code)

def view_sheet(request, id):
    '''View method to find and display a single
    :class:`~belfast.groupsheets.rdfmodels.TeiGroupSheet`

    :param id: TEI identifier for the Group sheet to be viewed
    '''

    context = {
        'extra_ns': {'bg': rdfns.BG, 'freebase': rdfns.FREEBASE},
        'page_rdf_type': 'bg:GroupSheet'
    }
    try:
        gs = TeiGroupSheet.objects.also('ark_list',
                                     'document_name') \
                               .get(id=id)
    except DoesNotExist:
        raise Http404

    # find the related rdf groupsheet object(s)
    # so we can display & link to sources
    rdfgs = groupsheet_by_url(gs.ark)  # todo: associate with tei or rdf gs model
    sources = [s for r in rdfgs for s in r.sources]

    context.update({'document': gs,
                   'page_rdf_url': getattr(gs, 'ark', None),
                   'sources': sources})
    return render(request, 'groupsheets/display.html', context)


# TODO: throughout, would be good to use etag & last-modified headers


def teixml(request, name):
    """Display the full TEI XML content for digitized groupsheets.

    :param name: name of the document to be displayed
    """
    try:
        doc = TeiDocument.objects.get(document_name=name)
    except DoesNotExist:
        raise Http404
    tei_xml = doc.serialize(pretty=True)
    return HttpResponse(tei_xml, content_type='application/xml')


@last_modified(rdf_lastmod)  # for now, list is based on rdf
def list_groupsheets(request):
    '''View to display a list of all Group sheets from the RDF data.  Includes
    logic to generate and filter by facets for digital editions, authors, coverage
    dates, and source collections.

    Looks for a :class:`~django.contrib.flatpages.models.FlatPage` for this url,
    and if found, passes to the template display at the top of the list of
    Group sheets.
    '''

    # get flatpage for this url, if any
    flatpage = get_flatpage(request)

    url_args = {}
    filters = {}
    filter_digital = request.GET.get('edition', None)
    if filter_digital is not None:
        filters['has_url'] = True
        url_args['edition'] = 'digital'

    filter_author = request.GET.get('author', None)
    if filter_author is not None:
        # filter is in slug form; use that to build local uri
        url_args['author'] = filter_author
        author_uri = local_uri(reverse('people:profile', args=[filter_author]),
                               request)
        filters['author'] = author_uri

    filter_source = request.GET.get('source', None)
    if filter_source is not None:
        url_args['source'] = filter_source
        # TODO: preferred label / slugs / local identifier for these?
        # currently arg is the uri
        filters['source'] = filter_source

    filter_time = request.GET.get('dates', None)
    if filter_time is not None:
        url_args['dates'] = filter_time
        filters['coverage'] = filter_time

    results = get_rdf_groupsheets(**filters)
    # TODO: support source filter; make more django-like

    # generate labels/totals for 'facet' filters
    digital_count = 0
    authors = defaultdict(int)
    sources = defaultdict(int)
    time_periods = defaultdict(int)
    for r in results:
        # if not already filtered on digital, get a count
        if filter_digital is None and r.url:
            digital_count += 1
        if filter_author is None:
            # use author list to ensure *all* authors are listed properly
            for author in r.author_list:
                authors[author] += 1
        if filter_source is None:
            for s in r.sources:
                sources[s] += 1
        if filter_time is None:
            time_periods[r.coverage] += 1

    # generate lists of dicts for easy sorting in django template
    authors = [{'author': k, 'total': v} for k, v in authors.iteritems()]
    sources = [{'source': k, 'total': v} for k, v in sources.iteritems()]
    time_periods = [{'time_period': k, 'total': v} for k, v in time_periods.iteritems()]

    facets = {'digital': digital_count, 'authors': authors, 'sources': sources,
              'time_periods': time_periods}

    url_suffix = ''
    url_suffix = urllib.urlencode(url_args)
    # if not empty, prepend & for easy combination with other url args
    if url_suffix != '':
        url_suffix = '&%s' % url_suffix

    # generate query args to remove individual filters
    filters = {}
    if filter_digital is not None:
        args = url_args.copy()
        del args['edition']
        filter_args = urllib.urlencode(args)
        filters['digital edition'] = '?' + (filter_args if filter_args else '')
    if filter_author is not None:
        args = url_args.copy()
        del args['author']
        # pull author display name from results
        # TODO: init rdfperson and use that label instead?
        if results:
            for a in results[0].author_list:
                # groupsheets may have multiple authors, so make sure
                # we get the correct label for the active filter
                if str(a.identifier) == author_uri:
                    filters["%s, %s" % (a.lastname, a.firstname)] = '?' + urllib.urlencode(args)
                    break

    if filter_source is not None:
        args = url_args.copy()
        del args['source']
        if results:
            # pull source name from results (TODO: shorter labels)
            for s in results[0].sources:
                # groupsheets may have multiple sources, so make sure
                # we get the correct label
                if str(s.identifier) == filter_source:
                    filters[s.name] = '?' + urllib.urlencode(args)
                    break

    if filter_time is not None:
        args = url_args.copy()
        del args['dates']
        filters[filter_time] = '?' + urllib.urlencode(args)


    return render(request, 'groupsheets/list.html',
                  {'documents': results, 'facets': facets,
                   'url_suffix': url_suffix, 'filters': filters,
                   'flatpage': flatpage})


def search(request):
    '''View for a simple keyword search on TEI Groupsheet content only.'''
    form = KeywordSearchForm(request.GET)

    context = {'form': form, 'page_rdf_type': 'schema:SearchResultsPage'}
    if form.is_valid():
        keywords = form.cleaned_data['keywords']
        # pagination todo (?)
        # page = request.REQUEST.get('page', 1)

        try:
            results = TeiGroupSheet.objects \
                                .filter(fulltext_terms=keywords) \
                                .order_by('-fulltext_score') \
                                .also('fulltext_score')
            context.update({'documents': results, 'keywords': keywords})
            # calculate total to trigger exist query so error can be caught
            results.count()
        except ExistDBException as err:
            logger.error('eXist query error: %s', err)
            context['query_error'] = True

    return render(request, 'groupsheets/search_results.html',
                  context)

belfast/groupsheets/templates/groupsheets/display.html
{% extends 'page_base.html' %}
{% load tei %} {% load static %}

{% block page-subtitle %} : {{ document.title }}{% endblock %}

{% block head-extras %}
  {% if document.ark %}
    <link href="{{ document.ark }}" rel="bookmark"/>
  {% endif %}
  <link rel="alternate" type="application/rdf+xml" href="{% url 'groupsheets:view' document.id %}RDF/"/>
  {# NOTE: not strictly an alternate (may contain multiple groupsheets), but close... #}
  <link rel="alternate" type="application/xml" href="{% url 'groupsheets:xml' document.document_name %}"/>
  {# styles specific to the poetry #}
  <link href="{% static 'css/poetry.css' %}" rel="stylesheet"/>
{% endblock %}

{% block body-attrs %}data-spy="scroll" data-target=".local-sidenav" data-offset-top="200"{% endblock %}

{% block page-content %}
<div class="row" id="top">
  </div>
  <div class="row">
  <div class="contents col-md-4 local-sidenav">
    {# use toc item titles for RDF title list #}
    {% for toc in document.toc_list %}
      {% for item in toc.items %}
      <meta property="dc:title" inlist="inlist" content="{{ item }}"/>
      {% endfor %}
    {% endfor %}

    {# NOTE: there is a table of contents item list, but it does not include ids #}
    {# generating toc from the actual poems instead #}
    <ul class="nav nav-list sidenav">
        {# heading must be in list to stay fixed #}
        {# <li><h4>{{ document.toc.title }}</h4></li> #}
        {# NOTE: hard-coding ToC heading because multi-author groupsheet displays oddly #}
        <li><h4>Workshop Poems</h4></li>
         {% for poem in document.poems %}
        {# display authors by section if groupsheet has multiple authors #}
        {% if document.multi_author %}
          {% ifchanged %}<li class="list-label">{{ poem.byline }}</li>{% endifchanged %}
        {% endif %}
          <li><a href="#{{ poem.id }}">{{ poem.title|default:'[untitled]' }}</a></li>
        {% endfor %}

    </ul>
  </div> {# end sidenav #}

  <div class="col-md-7">
    <h1 property="schema:name">{{ document.title }}</h1>
    <div>
      <p><strong>Time period</strong>: <span property="dc:coverage">{{ document.date }}</span></p>
      {# NOTE: using byline from the first poem rather than document.author in order to generate RDF person info #}
      <p><strong>Poet{{ document.authors|pluralize }}</strong>:
          {% for author in document.authors %}{{ author|format_tei}}{% if not forloop.last %}; {% endif %}{% endfor %}
        </p>
      {% if document.ark %}
      <p><strong>Permanent URL</strong>:
          <a href="{{ document.ark }}" rel="bookmark schema:URL">{{ document.ark }}</a></p>
      {% endif %}

      <p><strong>Source{{ sources|pluralize }}</strong>:
        {% for src in sources %}
        <a href="{{ src.access_url }}">{{ src.name }}</a>{% if not forloop.last %}; {% endif %}
        {% endfor %}
      </p>
    </div>

    {% for poem in document.poems %}
    {# NOTE: using ARK URL plus the poem id for poem URI #}
      <div class="poem" typeof="schema:CreativeWork freebase:book/poem" about="{{ document.ark}}#{{poem.id }}" id="{{ poem.id }}">
        <hr/>
        <a name="{{ poem.id }}">
          {% if poem.title %}
            <a href="#top" class="to-top"><span class="glyphicon glyphicon-chevron-up"></span>Back to top</a>
            <h3><span property="schema:name">{{ poem.title_node|format_tei }}</span></h3>
          {% endif %}
        </a>
        {{ poem.body|format_tei }}
        {% if poem.byline %}
          <p class="byline">{{ poem.back|format_tei }}</p>
        {% endif %}
      </div>
    {% endfor %}
    <a href="#top" class="to-top"><span class="glyphicon glyphicon-chevron-up"></span>Back to top</a>
    <p class="pull-right"><a href="{% url 'groupsheets:xml' document.document_name %}" rel="alternate">TEI XML</a></p>
  </div> {# end right column #}

 </div> {# end row #}
{% endblock %}

belfast/groupsheets/templates/groupsheets/list.html
{% extends 'page_base.html' %}
{% load tei %}

{% block page-subtitle %} : Group Sheets{% endblock %}

{% block page-content %}

  <h1 property="schema:name">Group Sheets</h1>
  {% if flatpage %}
    {% include "flatpages/snippets/flatpage_content.html" %}
  {% endif %}
<div class="clearfix"></div>


<div class="row">
  <div class="col-md-3 col-sm-4 sidebar">
    <h4>Filter Group sheets <a href="#" class="toggle-section btn btn-primary"><span class="glyphicon glyphicon-chevron-down dwn"></span><span class="glyphicon glyphicon-chevron-up up"></span></a></h4>
    <div class="collaspe-section collasped" style="display:none;">
        {% if filters %}{# display filters currently in effect, with link to remove #}
          <ul class="active-filters">
            {% for label, link in filters.iteritems %}
            <li><a href="{{ link }}">{{ label }} <span class="small text-danger"><span class="glyphicon glyphicon-remove-sign"></span></span></a></li>
            {% endfor %}
        </ul>
        {% endif %}

        <hr/>
        {% if facets.digital %}
        <ul>
            <li><a href="?edition=digital{{ url_suffix }}">digital editions
                <span class="text-muted">({{ facets.digital }})</span>  </a> </li>
        </ul>
        {% endif %}

        {% if facets.time_periods %}
        <p><b>Time Period</b></p>
        <ul>
            {% for f in facets.time_periods|dictsort:"time_period" %}
            <li><a href="?dates={{ f.time_period|default:"undetermined" }}{{ url_suffix }}">{{ f.time_period|default:"Undetermined" }}
                <span class="text-muted">({{ f.total }})</span></a> </li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if facets.authors %}
        <p><b>Author</b></p>
        <ul>
            {% for f in facets.authors|dictsortreversed:"total" %}
            <li><a href="?author={{ f.author.slug }}{{ url_suffix }}">{{ f.author.lastname }}, {{ f.author.firstname }}
                <span class="text-muted">({{ f.total }})</span></a></li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if facets.sources %}
        <p><b>Source</b></p>
        <ul>
            {% for s in facets.sources|dictsortreversed:"total" %}  {# TODO: need to use short names here! #}
            <li><a href="?source={{ s.source.identifier|urlencode }}{{ url_suffix }}">{{ s.source.name }}
                <span class="text-muted">({{ s.total }})</span></a> </li>
            {# NOTE: urlencode required since collection URIs include #anchors which otherwise get lost #}
            {% endfor %}
        </ul>
        {% endif %}
    </div>
  </div> {# end sidebar #}

  <div class="col-md-9 col-sm-8">

    <h2>Displaying {{ documents|length }} Group sheet{{ documents|pluralize }}.</h2>

    <ul class="groupsheet-list list-group">
        {% for doc in documents %}
        <li class="list-group-item">
            {% include 'groupsheets/snippets/list_groupsheet.html' %}
        </li>
        {% endfor %}
    </ul>
  </div>

</div> {# end rows #}
{% endblock %}

belfast/groupsheets/templates/groupsheets/search_results.html
{% extends 'site_base.html' %}
{% load tei %}

{% block page-subtitle %} : Search Results{% endblock %}

{% block content %}
<div class="container">
<h1>Search Results</h1>

<div class="span7">
  {% if form.errors %}
    {% for field, msg in form.errors.iteritems %}
      {{ msg }}
    {% endfor %}
  {% elif query_error %}
  {# TODO: more detail here would probably be useful (could be anything) #}
  <p>There was an error processing your search. </p>
  {% else %}

  <p>Found {{ documents.count }} result{{ documents.count|pluralize }}
    for <strong>{{ keywords }}</strong>.
    Results sorted by relevance.</p>

    {% for document in documents %}
    <div>
      {# note: relevance score available as document.fulltext_score #}
      {% url 'groupsheets:view' id=document.id as document_url %}
      <p><a href="{{ document_url }}">{{ document.title }}</a></p>
      {# TODO: might be nice if groupsheet list and search result list were closer... #}
      <ul>
        {% for poem in document.poems %}
        <li><a href="{{ document_url }}#{{ poem.id }}">{{ poem.title }}</a></li>
        {% endfor %}
      </ul>
    </div>
    {% endfor %}

  {% endif %}  {# valid form #}
</div>

</div>
{% endblock %}