belfast/people/urls.py
from django.conf.urls import patterns, include, url
from belfast.people import views

urlpatterns = patterns('',
    url(r'^$', views.list, name='list'),
    url(r'^(?P<id>[a-z0-9:_-]+)/$', views.profile, name='profile'),
    url(r'^(?P<id>[a-z0-9:_-]+)/ego.json$', views.egograph_js, name='egograph-js'),
    # url(r'^(?P<id>[a-z0-9:_-]+)/ego-graph/$', views.egograph, name='egograph'),
    url(r'^(?P<id>[a-z0-9:_-]+)/ego-graph/node/$', views.egograph_node_info, name='egograph-node'),
)

belfast/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib.sitemaps import FlatPageSitemap

from belfast.pages import views as pages_views
from belfast.sitemaps import OtherViewsSitemap
from belfast.groupsheets.sitemaps import GroupSheetsSitemap, XmlDocumentsSitemap
from belfast.people.sitemaps import ProfileSitemap

# enable django db-admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', pages_views.site_index, name='site-index'),
    url(r'^groupsheets/', include('belfast.groupsheets.urls',
        namespace='groupsheets')),
    url(r'^people/', include('belfast.people.urls',
        namespace='people')),
    url(r'^network/', include('belfast.network.urls',
        namespace='network')),
    url(r'^', include('belfast.pages.urls')),
    # add redirect for favicon at root of site
    (r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True)),
    # Examples:
    # url(r'^$', 'belfast.views.home', name='home'),
    # url(r'^belfast/', include('belfast.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),


    # belfast group rdf ontology
    #   http://belfastgroup.library.emory.edu/ontologies/2013/6/belfastgroup/
    url(r'^ontologies/2013/6/belfastgroup/$',
        TemplateView.as_view(template_name='bg-ontology.xml',
        content_type='text/xml'), name='bg-ontology'),
    url(r'^robots\.txt$',
        TemplateView.as_view(template_name='robots.txt',
        content_type='text/plain'), name='robots.txt'),
)

# xml sitemaps for search-engine discovery
sitemaps = {
    'groupsheets': GroupSheetsSitemap,
    'xmlgroupsheets': XmlDocumentsSitemap,
    'profiles': ProfileSitemap,
    'flatpages': FlatPageSitemap,
    'other': OtherViewsSitemap
}

urlpatterns += patterns('django.contrib.sitemaps.views',
    (r'^sitemap\.xml$', 'index', {'sitemaps': sitemaps}),
    (r'^sitemap-(?P<section>.+)\.xml$', 'sitemap', {'sitemaps': sitemaps}),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

belfast/people/models.py
from django.db import models
import rdflib

from django_image_tools.models import Image

from belfast.util import rdf_data
from belfast.groupsheets.rdfmodels import RdfArchivalCollection
from belfast.people.rdfmodels import RdfPerson


class ProfilePicture(models.Model):
    '''Profile picture - an image or photograph associated with an
    :class:`belfast.people.rdfmodels.RdfPerson` in the RDF data with a local profile,
    linked via person URI.'''

    # Fields: creator, title, date, publisher, publisher URL, collection, statement of permissions
    #: URI for the person depicted or represented by the picture
    person_uri = models.URLField(verbose_name='Person', unique=True)
    #: :class:`django_image_tools.models.Image`
    image = models.ForeignKey(Image, related_name='profilepicture_set')
    #: date of the photo, if known
    date = models.CharField(max_length=255,
        help_text='Date of the photo, if known', blank=True)
    #: collection URI - archival collection the picture came from, if MARBL content
    collection_uri = models.URLField(blank=True, null=True,
        help_text='MARBL Archival collection source for the original picture (for MARBL content)',
        verbose_name='Archival Collection')
    #: photographer or creator of the image
    creator = models.CharField(max_length=255,
        help_text='Photographer or whoever else is responsible for creating the image, if known',
        blank=True)
    #: URL for the photographer's website
    creator_url = models.URLField(blank=True,
        verbose_name='Creator Website', help_text='''Photographer website URL, if available''')
    #: photo publisher, if applicable
    publisher = models.CharField(max_length=255, blank=True,
        help_text='Name of the publisher, if applicable')
    #: publisher URH, if there is a publisher
    publisher_url = models.URLField(blank=True,
        verbose_name='Publisher Website', help_text='''Publisher URL, if known;
        used with publisher name to generate a link on profile page''')
    #: permissions statement
    permissions = models.TextField(help_text='Statement of Permissions')

    def __unicode__(self):
        return self.image.title

    @property
    def rdfperson(self):
        'associated :class:`~belfast.people.rdfmodels.RdfPerson`'
        return RdfPerson(rdf_data(), rdflib.URIRef(self.person_uri))

    @property
    def person(self):
        'person name'
        return self.rdfperson.name

    @property
    def rdfcollection(self):
        ''':class:`belfast.groupsheets.rdfodels.RdfArchivalCollection` this image
        came from, if :attr:`collection_uri` is set.'''
        if self.collection_uri is not None:
            return RdfArchivalCollection(rdf_data(), rdflib.URIRef(self.collection_uri))

    @property
    def collection(self):
        ''' collection name'''
        if self.rdfcollection is not None:
            return self.rdfcollection.name

    @property
    def title(self):
        'image title'
        if self.image:
            return self.image.title

    @property
    def thumbnail(self):
        'thumbnail of django-image-tools Image, for use in admin'
        if self.image:
            return self.image.thumbnail

belfast/people/views.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse
from django.shortcuts import render
from django.views.decorators.http import last_modified
import json
from networkx.readwrite import json_graph, gexf
import rdflib

from belfast import rdfns
from belfast.util import rdf_data, rdf_data_lastmodified, \
    network_data_lastmodified, local_uri
from belfast.groupsheets.rdfmodels import get_rdf_groupsheets
from belfast.people.rdfmodels import profile_people, RdfPerson, RdfPoem
from belfast.network.util import annotate_graph


def rdf_lastmod(request, *args, **kwargs):
    return rdf_data_lastmodified()


def rdf_nx_lastmod(request, *args, **kwargs):
    return max(rdf_data_lastmodified(), network_data_lastmodified())


@last_modified(rdf_lastmod)  # for now, list is based on rdf
def list(request):
    'Display a list of people one remove from the Belfast Group.'
    people = profile_people()
    # filter to only people with a description
    people = [p for p in people if p.has_profile]

    # filter to people with a profile photo loaded, if requested
    # (defaults to true)
    if getattr(settings, 'REQUIRE_PROFILE_PICTURE', True):
        people = [p for p in people if p.picture]

    return render(request, 'people/list.html',
                  {'people': people})

@last_modified(rdf_nx_lastmod)  # uses both rdf and gexf
def profile(request, id):
    'Display a profile page for a single person associated with the Belfast Group.'
    uri = local_uri(reverse('people:profile', args=[id]), request)
    g = rdf_data()
    uriref = rdflib.URIRef(uri)
    # check that the generated URI is actually a person in our rdf dataset;
    # if not, 404
    if not (uriref, rdflib.RDF.type, rdfns.SCHEMA_ORG.Person) in g:
        raise Http404
    person = RdfPerson(g, uriref)
    groupsheets = get_rdf_groupsheets(author=uri) # TODO: move to rdfperson class

    return render(request, 'people/profile.html',
                  {'person': person, 'groupsheets': groupsheets,
                  'page_rdf_type': 'schema:ProfilePage'})


@last_modified(rdf_nx_lastmod)  # uses both rdf and gexf
def egograph_js(request, id):
    'Egograph information as JSON for a single person.'
    uri = local_uri(reverse('people:profile', args=[id]), request)
    g = rdf_data()
    person = RdfPerson(g, rdflib.URIRef(uri))
    graph = person.ego_graph(radius=1,
                             types=['Person', 'Organization', 'Place'])
    # annotate nodes in graph with degree
    #  NOTE: not a directional graph, so in/out degree not available

    graph = annotate_graph(graph, fields=['degree', 'in_degree', 'out_degree',
                                          'betweenness_centrality',
                                          'eigenvector_centrality'])

    data = json_graph.node_link_data(graph)
    return HttpResponse(json.dumps(data), content_type='application/json')


# NOTE: egograph view no longer in use, but might want to consider
# switching network graph tab of profile page to be loaded via ajax

# @last_modified(rdf_nx_lastmod)  # uses both rdf and gexf (?)
# def egograph(request, id):
#     person = get_object_or_404(Person, slug=id)
#     return render(request, 'people/ego_graph.html', {'person': person})

def egograph_node_info(request, id):
    '''HTML snippet to provide information about a node in the egograph.
    Intended to be loaded and displayed via AJAX.

    Some overlap with :meth:`belfast.network.views.node_info`.
    '''

    # id is the person to whom this node is connected
    uri = local_uri(reverse('people:profile', args=[id]), request)
    g = rdf_data()
    ego_person = RdfPerson(g, rdflib.URIRef(uri))

    # NOTE: some overlap here with networks node_info view

    # id param is the node we want information
    node_id = request.GET.get('id', None)
    if node_id is None:
        raise Http404

    node_uri = rdflib.URIRef(node_id)
    # TODO: better to get relations from gexf or rdf ?
    graph = gexf.read_gexf(settings.GEXF_DATA['full'])
    node = graph.node[node_id]
    context = {'node': node}

    if node.get('type', None) == 'Person':
        # init rdf person
        person = RdfPerson(rdf_data(), rdflib.URIRef(node_id))
        context['person'] = person

    # determine relation between node and ego-center
    rels = set(g.predicates(ego_person.identifier, node_uri))
    # TODO: may want to display other relationships?

    # special case: if "mentions", should be a poem; find for display/link
    if rdfns.SCHEMA_ORG.mentions in rels:
        txts = set(g.subjects(rdfns.SCHEMA_ORG.mentions, node_uri)) \
               - set([ego_person.identifier])
        if txts:
            poems = [RdfPoem(g, p) for p in txts]
            # explicitly skip any non-poems, just in case
            context['poems'] = [p for p in poems if rdfns.FREEBASE["book/poem"] in p.rdf_types]

    return render(request, 'network/node_info.html', context)

belfast/people/templates/people/ego_graph.html
{% load static %}
{# structured for inclusion as a profile tab #}

<p>Force-directed ego graph of people, places, and organizations directly connected to
  <b>{{ person.fullname }}</b>.</p>

{% comment %} {# this help text should be redundant now that there is help info included in graph controls #}
<p>Nodes are colored by type.  Mouse over a label to see the text more clearly.
  You can drag nodes to move them apart and investigate connections;
  double-click a fixed node to return it back to automatic placement.</p>
{% endcomment %}

{% include 'network/snippets/graph_with_controls.html' %}

  {# TODO: make ego-graph radius configurable / user-editable ? #}
  {# <link href="{% static 'js/jquery-ui/css/ui-lightness/jquery-ui-1.10.3.custom.min.css' %}" rel="stylesheet" media="screen"/> #}
 <link href="{% static 'js/jquery-ui/css/redmond/jquery-ui.min.css' %}" rel="stylesheet" media="screen"/>
  <script type="text/javascript" src="{% static 'js/jquery-ui/js/jquery-ui-1.10.3.custom.min.js' %}"></script>
  <script src="{% static 'js/d3.min.js' %}" charset="utf-8"></script>
  <link type="text/css" href="{% static 'css/d3.force.css' %}" rel="stylesheet" media="screen"/>
   <script type="text/javascript" src="{% static 'js/d3.force.js' %}"></script>

   <script type="text/javascript">
    $(document).ready(function(){

      //This function lets us delay the window resize event before running the drawCharts function.
      jQuery.fn.resize_delayed = function ( func, duration ){
          this.resize(function() {
              clearTimeout( window.____resize_delayed );
              window.____resize_delayed = setTimeout( func, duration);
          });
      };

      //This is were we define the network graph
      function drawGraph(options){
        var setWidth = $("#network-graph").width();

        //if the graph's parent container is hidden (not the active tab), we can't get the width
        //take the tab-content width instead.

        if(setWidth==null || setWidth<100){
          setWidth = $(".tab-content").width();
        }

        ForceGraphControls({
          target: "#graph-controls",
          graph_options: {
              url: "{% url 'people:egograph-js' id=person.slug %}",
              target: "#network-graph",
              width: setWidth,
              height: 500,
              highlight: ['{{ person.identifier }}'],
              labels: true,
              node_info_url: "{% url 'people:egograph-node'  id=person.slug %}",
              gravity: 1.0,
              link_distance: 75,
              charge: -500
          }
        });
      }

      //Call drawChart on load
      drawGraph();
      
      //When the window is resized, call the drawGraph function to redraw chart
      $(window).resize_delayed(function(){
        
        drawGraph({setWidth:$("#network-graph").width()});
        
      },500);

    });
   </script>

belfast/people/templates/people/list.html
{% extends 'page_base.html' %}
{% load static %}

{% block page-subtitle %} : Members{% endblock %}
{% block head-extras %}
  <script src="{% static 'js/masonry.min.js' %}"></script>
{% endblock %}


{% block page-content %}
<h1 property="schema:name">People associated with the Belfast Group</h1>

<div id="bios">
  {% for person in people %}
  <div class="panel">
    <div class="thumbnail text-center">
          {% if person.picture %}
          <a href="{{ person }}">
            <figure>
              <img src="{{ person.picture.image.get__thumbnail }}" alt="{{ person.picture.image.alt_text }}"
                 title="{{ person.picture.image.title }}">
            </figure>
          </a>
          {% endif %}
          <div class="caption">
            <a href="{{ person }}">
            {% if person.lastname and person.firstname %}
              {{ person.firstname }} {{ person.lastname }}
            {% else %} {{ person.name }}
            {% endif %}
            </a>
            {# NOTE: would be nice to include count of connections/groupsheet; currently very SLOW #}
            {% comment %}
            {% if person.connected_people %}
              <p>{{ person.connected_people|length }} connected people</p>
            {% endif %}
            {% if person.connected_organizations %}
              <p>{{ person.connected_organizations|length }} connected organizations</p>
            {% endif %}
            {% endcomment %}
        </div> {# end caption #}
    </div> {# end thumbnail #}
  </div> {# end panel #}
  {% endfor %}
</div> {# end bios #}
{% endblock %}

{% block endbody %}
  <script src="{% static 'js/belfast.js' %}"></script>
{% endblock %}

belfast/people/templates/people/profile.html
{% extends 'page_base.html' %}
{% load static %}

{% block page-subtitle %} : Members : {{ person.name }}{% endblock %}

{% block head-extras %}
{% endblock %}

{% block page-content %}
<div rel="schema:about">
  <div typeof="schema:Person">

    <h1>
      {% if person.lastname and person.firstname %}
       <span property="schema:givenName">{{ person.firstname }}</span>  <span property="schema:familyName">{{ person.lastname }}</span>
      {% else %}
      <span property="schema:name">{{ person.name }}</span>
      {% endif %}
    </h1>
    <div class="row">
      {% if person.picture %}
      {% with pic=person.picture %}
        <div class="col-xs-6 col-md-4 pull-right" rel="schema:image">
            {# admin edit link, if user has permission to edit profile pictures #}
            {% if perms.people.change_profilepicture %}
                <a class="pull-right btn" href="{% url 'admin:people_profilepicture_change' pic.id %}"><span class="glyphicon glyphicon-edit"></span></a>
            {% endif %}
          <figure typeof="schema:ImageObject" class="thumbnail text-center">
              <h4 property="schema:caption">{{ pic.title }}</h4>
              <img src="{{ pic.image.get__profile }}" alt="{{ pic.image.alt_text }}" title="{{ pic.image.title }}"
                property="schema:contentUrl"/>
              <figcaption class="caption">
                <ul class="list-inline small">
                  {% if pic.date %}<li property="schema:dateCreated">{{ pic.date }}</li>{% endif %}
                  {% if pic.creator %}<li property="schema:author">
                      {% if pic.creator_url %}
                      <a href="{{ pic.creator_url }}">{{ pic.creator }}</a>
                      {% else %}{{ pic.creator }}{% endif %}
                      </li>{% endif %}
                  {% if pic.publisher %}
                  <li rel="schema:publisher">
                    <span typeof="schema:Organization">
                      {% if pic.publisher_url %}
                      <a property="schema:url" href="{{ pic.publisher_url }}"><span property="schema:name">{{ pic.publisher }}</span></a>
                      {% else %}<span property="schema:name">{{ pic.publisher }}</a>{% endif %}
                    </span>
                  </li>
                  {% endif %}
                </ul>
                {% if pic.collection %}
                <p><small><a href="{{ pic.rdfcollection }}">{{ pic.collection }}</a></small></p>
                {% endif %}
                {% if pic.permissions %}
                <p><i class="small">{{ pic.permissions }}</i></p>
                {# NOTE: if url, could use schema:license #}
                {% endif %}

              </figcaption><!--/.caption-->
          </figure>
        </div>
        {% endwith %}
      {% endif %}

    <div class="col-md-8">
      {% comment %}  {# Using local profile images instead of dbpedia thumbnails #}
      {% if person.dbpedia.thumbnail %}
      <div class="pull-right">
        <img src="{{ person.dbpedia.thumbnail }}"/>
        <p><small><i>image via <a href="{{ person.dbpedia.wikipedia_url }}">Wikipedia</a></i></small></p>
      </div>
      {% endif %}
      {% endcomment %}

      {# suppressing rdf occupation, locations, birth date & place - redundant with description #}
      {% comment %}
      {% if person.occupation %}
      <p><b>Occupation:</b> {{ person.occupation|join:', ' }}</p>
      {% endif %}

      {% if person.locations %}
      <p><b>Locations:</b>
          {# for now, link to outside URI location; eventually may want in-site links #}
        {% for loc in person.locations %}
        <a href="{{ loc.identifier }}">{{ loc }}</a>{% if not forloop.last %}; {% else %}.{% endif %}
        {% endfor %}
        </p>
      {% endif %}

      {% if person.birthdate %}
      <p>Born {{ person.birthdate }}
          {% if person.birthplace %}
          in <a href="{{ person.birthplace.identifier }}">{{ person.birthplace }}</a>{% endif %}.</p>
      {% endif %}
      {% endcomment %}

      {# keeping redundant rdf info invisible, but make some of it available via rdfa #}
      {% for occ in person.occupation %}
      <span property="schema:jobTitle" content="{{ occ }}"/>
      {% endfor %}
      {% if person.birthdate %}<span property="schema:birthDate" content="{{ person.birthdate }}"/>{% endif %}

      {% if person.dbpedia_uri %}<a property="schema:sameAs" href="{{ person.dbpedia_uri}}"></a>{% endif %}
      {% if person.viaf_uri %}<a property="schema:sameAs" href="{{ person.viaf_uri}}"></a>{% endif %}


      {% if person.description %}
      <p property="schema:description" class="description">{{ person.description }}
        {% if person.description_context and person.desc_context_name %}
        {# link to the source of the description *if* it has a label (i.e., findingaid where the description comes from) #}
        <small><i>(<a href="{{ person.description_context }}">{{ person.desc_context_name }}</a>)</i></small>
        {% endif %}
      </p>
      {% elif person.dbpedia.description %}
      <p>{{ person.dbpedia.description }}
        <small><i>({% if person.dbpedia.wikipedia_url %}<a href="{{ person.dbpedia.wikipedia_url }}">Wikipedia</a>{% else %}Wikipedia{% endif %})</i></small></p>
        {% endif %}

    </div>
  </div><!-- /.row -->

  <div class="row">
    <ul class="nav nav-tabs nav-justified" id="vizTab">
      {% if groupsheets %}
      <li class="active"><a href="#groupsheets">Group Sheets</a></li>
      {% endif %}
      {# only display connections & network tab if there are any #}
      {% if person.connected_people|length or person.connected_organizations|length %}
      <li {% if not groupsheets %}class="active"{% endif %}><a href="#graph">Network Graph</a></li>
      <li><a href="#connections">Connections</a></li>
      {% endif %}

    </ul>

    <div class="tab-content">
      {% if groupsheets %}
      <div class="tab-pane active" id="groupsheets">
        <ul class="groupsheet-list list-group">
          {% for doc in groupsheets %}
            <li class="list-group-item">{% include 'groupsheets/snippets/list_groupsheet.html' with profile=True %}</li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}

      {% if person.connected_people|length or person.connected_organizations|length %}
      <div class="tab-pane {% if not groupsheets %}active{% endif %}" id="graph">
        {% include "people/ego_graph.html" %}
      </div>

      <div class="tab-pane" id="connections">

        {% if person.connected_people %}
        <h4>People</h4>
        <ul>
          {% for conn, rel_info in person.connected_people %}
          <li>
            {% if conn.has_profile %} {# if connected person has a profile, link to it #}
            <a href="{{ conn.identifier }}">{{ conn.fullname }}</a>
            {% else %}
            {{ conn.fullname }}
            {% endif %}

            {# link to viaf, wikipedia with icons #}
            {% if conn.viaf_uri %}
            <a href="{{ conn.viaf_uri }}"><img src="{% static 'img/viaf.png' %}" alt="VIAF"/></a>
            {% endif %}
            {% if conn.dbpedia_uri %}
            {# link to wikipedia page if we can; if not, link to dbpedia #}
            <a href="{{ conn.dbpedia.link }}">
              <img src="{% static 'img/wikipedia.png' %}" alt="Wikipedia"/>
            </a>
            {% endif %}

            {% if rel_info.0 %} - {{ rel_info.0|join:', '}}{% endif %}
            {% if debug %}<small>(weight: {{ rel_info.1 }})</small>{% endif %}
          </li>
          {% endfor %}
        </ul>
        {% endif %}

        {% if person.connected_organizations %}
        <h4>Organizations</h4>
        <ul>
          {% for conn, rel_info in person.connected_organizations %}
          <li>{{ conn.name }}
            {# link to viaf, wikipedia with icons #}
            {% if conn.viaf_uri %}
            <a href="{{ conn.viaf_uri }}"><img src="{% static 'img/viaf.png' %}" alt="VIAF"/></a>
            {% endif %}
            {% if conn.dbpedia_uri %}
            {# link to wikipedia page if we can; if not, link to dbpedia #}
            <a href="{% firstof conn.dbpedia.wikipedia_url conn.dbpedia %}"><img src="{% static 'img/wikipedia.png' %}" alt="Wikipedia"/></a>
            {% endif %}

            {% if rel_info %} - {{ rel_info.0|join:', '}}{% endif %}
            {% if debug %}<small>(weight: {{ rel_info.1 }})</small>{% endif %}
          </li>
          {% endfor %}
        </ul>
        {% endif %}
      </div>

      {% endif %}
    </div>

  </div> {# person #}
</div> {# about #}
</div>
<script>
$(function () {
  $('#vizTab a').on('click',function (e) {
    e.preventDefault();
    $(this).tab('show');
  });
});
</script>
{% endblock %}