belfast/network/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from belfast.network import views

urlpatterns = patterns('',
    url(r'^$', views.overview, name='overview'),
    url(r'^full/$', views.force_graph, name='force-graph'),
    url(r'^chord/$', views.chord_diagram, name='chord'),
    url(r'^(?P<mode>full|adjacency).json$', views.full_js, name='js'),
#    url(r'^adjacency.json$', views.adjacency_js, name='adjacency-js'),

    url(r'^belfast-group/$', views.group_people, name='bg'),
    url(r'^belfast-group.json$',
        views.group_people_js, {'output': 'full'}, name='bg-js'),
    url(r'^belfast-group_matrix.json$',
        views.group_people_js, {'output': 'adjacency'}, name='bg-js-matrix'),
    url(r'^belfast-group/groupsheets/$', views.group_people,
        {'mode': 'groupsheet-model'}, name='bg-gs'),
    url(r'^belfast-group/groupsheets.json$', views.group_people_js,
        {'mode': 'groupsheet-model'}, name='bg-gs-js'),
    url(r'^map/$', views.map, name='map'),
    url(r'^map.json$', views.map_js, name='map-js'),
    url(r'^node/$', views.node_info, name='node-info'),

    # network data in GEXF format
    url(r'^(?P<mode>all|group-people|groupsheets).gexf$', views.gexf_content, name='gexf'),
)

belfast/people/urls.py
from django.conf.urls import patterns, include, url
from belfast.people import views

urlpatterns = patterns('',
    url(r'^$', views.list, name='list'),
    url(r'^(?P<id>[a-z0-9:_-]+)/$', views.profile, name='profile'),
    url(r'^(?P<id>[a-z0-9:_-]+)/ego.json$', views.egograph_js, name='egograph-js'),
    # url(r'^(?P<id>[a-z0-9:_-]+)/ego-graph/$', views.egograph, name='egograph'),
    url(r'^(?P<id>[a-z0-9:_-]+)/ego-graph/node/$', views.egograph_node_info, name='egograph-node'),
)

belfast/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib.sitemaps import FlatPageSitemap

from belfast.pages import views as pages_views
from belfast.sitemaps import OtherViewsSitemap
from belfast.groupsheets.sitemaps import GroupSheetsSitemap, XmlDocumentsSitemap
from belfast.people.sitemaps import ProfileSitemap

# enable django db-admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', pages_views.site_index, name='site-index'),
    url(r'^groupsheets/', include('belfast.groupsheets.urls',
        namespace='groupsheets')),
    url(r'^people/', include('belfast.people.urls',
        namespace='people')),
    url(r'^network/', include('belfast.network.urls',
        namespace='network')),
    url(r'^', include('belfast.pages.urls')),
    # add redirect for favicon at root of site
    (r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True)),
    # Examples:
    # url(r'^$', 'belfast.views.home', name='home'),
    # url(r'^belfast/', include('belfast.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),


    # belfast group rdf ontology
    #   http://belfastgroup.library.emory.edu/ontologies/2013/6/belfastgroup/
    url(r'^ontologies/2013/6/belfastgroup/$',
        TemplateView.as_view(template_name='bg-ontology.xml',
        content_type='text/xml'), name='bg-ontology'),
    url(r'^robots\.txt$',
        TemplateView.as_view(template_name='robots.txt',
        content_type='text/plain'), name='robots.txt'),
)

# xml sitemaps for search-engine discovery
sitemaps = {
    'groupsheets': GroupSheetsSitemap,
    'xmlgroupsheets': XmlDocumentsSitemap,
    'profiles': ProfileSitemap,
    'flatpages': FlatPageSitemap,
    'other': OtherViewsSitemap
}

urlpatterns += patterns('django.contrib.sitemaps.views',
    (r'^sitemap\.xml$', 'index', {'sitemaps': sitemaps}),
    (r'^sitemap-(?P<section>.+)\.xml$', 'sitemap', {'sitemaps': sitemaps}),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

belfast/network/models.py
# no db models for this app

belfast/network/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.views.decorators.http import last_modified
from django.contrib.flatpages.models import FlatPage
import json
import logging
import networkx as nx
from networkx.readwrite import json_graph, gexf
import rdflib
from StringIO import StringIO

from belfast.util import network_data, rdf_data,  \
    rdf_data_lastmodified, network_data_lastmodified, normalize_whitespace, \
    relative_flatpage_url, get_flatpage
from belfast.rdfns import BELFAST_GROUP_URI
from belfast.groupsheets.rdfmodels import RdfGroupSheet
from belfast.people.rdfmodels import RdfOrganization, RdfPerson, find_places
from belfast.network.util import annotate_graph


logger = logging.getLogger(__name__)


def rdf_lastmod(request, *args, **kwargs):
    return rdf_data_lastmodified()


def rdf_nx_lastmod(request, *args, **kwargs):
    return max(rdf_data_lastmodified(), network_data_lastmodified())


def overview(request):
    '''Overview/intro page for network graphs and maps, with links to the
    network graphs, chord diagrams, and maps.

    Looks for a :class:`~django.contrib.flatpages.models.FlatPage` for this url,
    and if found, passes to the template to include in display.  If no
    page is found, results in a 404 not found error.
    '''
    # get flatpage for this url; if not available, 404
    fpage = get_object_or_404(FlatPage,
        url=relative_flatpage_url(request), sites__id=settings.SITE_ID)
    return render(request, 'network/overview.html', {'flatpage': fpage})

def _network_graph(min_degree=1, **kwargs):
    graph = network_data().copy()   # don't modify the original network

    rdfgraph = rdf_data()
    # filter graph by type of node
    types = ['Person', 'Organization', 'Place', 'BelfastGroupSheet']

    for n in graph.nodes():
        if ('type' not in graph.node[n] or \
           graph.node[n]['type'] not in types) :
            graph.remove_node(n)
            continue

        # use groupsheets to infer a connection between the author
        # of the groupsheet and the group itself
        # FIXME: this needs to be in data prep/clean, NOT here
        # TODO: should be handled in prep now; confirm and then remove this logic
        if graph.node[n]['type'] == 'BelfastGroupSheet':

            sheet = RdfGroupSheet(rdfgraph, rdflib.URIRef(n))
            # FIXME: error handling when author is not in the graph?
            # should probably at least log this...
            if sheet.author and unicode(sheet.author.identifier) in graph:
                graph.add_edge(unicode(sheet.author.identifier),
                               BELFAST_GROUP_URI, weight=4)

            # remove the groupsheet itself from the network, to avoid
            # cluttering up the graph with too much information
            #graph.add_edge(n, BELFAST_GROUP_URI, weight=5)
            graph.remove_node(n)

    # AFTER filtering by type, filter out by requested minimum degree

    removed = 0
    for n in graph.nodes():
        if graph.degree(n) < min_degree:
            removed += 1
            graph.remove_node(n)

    logger.info('removed %d nodes with degree less than %d' % (removed, min_degree))

    return graph


@last_modified(rdf_nx_lastmod)
def full_js(request, mode):
    '''Return full network graph data as JSON.  Optionally filter
    the data by minimum degree, if min_degree is specified as a url parameter.
    When generating the node and link data, nodes are annotated with
    degree, in degree, out degree, betweenness centrality, and eigenvector
    centrality if available.  (In/out degree is only available for directed
    graphs.)


    :param mode: full - node and link data; adjacency - adjacency matrix,
        used to construct a chord diagram

    .. deprecated:: 1.0

       This network graph is too large to be usable or viewable in a
       browser/javascript display environment, and should not be used;
       :meth:`group_people` should be used instead.
    '''


    # optionally filter by minimum degree
    min_degree =  request.GET.get('min_degree', None)
    filter = {}
    if min_degree:
        filter['min_degree'] = int(min_degree)

    graph = _network_graph(**filter)
    if mode == 'full':
        graph = annotate_graph(graph, fields=['degree', 'in_degree', 'out_degree',
                                              'betweenness_centrality',
                                              'eigenvector_centrality'])
        # standard nodes & links data
        data = json_graph.node_link_data(graph)

    if mode == 'adjacency':
        # adjacency matrix for generating chord diagram
        matrix = nx.linalg.graphmatrix.adjacency_matrix(graph)
        data = matrix.tolist()
    return HttpResponse(json.dumps(data), content_type='application/json')


@last_modified(rdf_nx_lastmod)
def full_gexf(request):
    '''Generate the same Belfast Group network data exposed in :meth:`full_js`
    in the GEXF format, for download and use in tools like Gephi.'''
    graph = _network_graph()
    buf = StringIO()
    gexf.write_gexf(graph, buf)
    response = HttpResponse(buf.getvalue(), content_type='application/gexf+xml')
    response['Content-Disposition'] = 'attachment; filename=belfastgroup.gexf'
    return response


@last_modified(rdf_nx_lastmod)
def gexf_content(request, mode):
    '''Make network data available as GEXF files for download and use in
    tools like Gephi.'''
    if mode == 'all':
        graph = network_data()
    elif mode == 'group-people':
        # filtered graph of people/places/organizations used for
        # first BG network graph displayed on the site
        # - same data used in :meth:`full_js`
        graph = _network_graph()
    elif mode == 'groupsheets':
        graph = gexf.read_gexf(settings.GEXF_DATA['bg1'])

    buf = StringIO()
    gexf.write_gexf(graph, buf)
    response = HttpResponse(buf.getvalue(), content_type='application/gexf+xml')
    response['Content-Disposition'] = 'attachment; filename=belfastgroup-%s.gexf' % mode
    return response


@last_modified(rdf_nx_lastmod)
def force_graph(request):
    '''Display a force-directed graph of the entire network.

    .. deprecated:: 1.0

       This network graph is too large to be usable or viewable in a
       browser/javascript display environment, and should not be used;
       :meth:`group_people` should be used instead.
    '''
    return render(request, 'network/graph.html')


@last_modified(rdf_nx_lastmod)
def chord_diagram(request):
    '''Display a circular chord diagram of the Belfast Group network.

    If a :class:`~django.contrib.flatpages.models.FlatPage` is found for
    this url, it is passed to the template to include in display.
    '''
    fpage = get_flatpage(request)
    return render(request, 'network/chord.html', {'flatpage': fpage})

@last_modified(rdf_nx_lastmod)
def group_people(request, mode='egograph'):
    '''Display a force-directed graph of people associated with the
    Belfast Group.

    :param mode: egograph: display people directly connected to the
       Belfast Group; groupsheet-model display a network model generated
       from information about the Group sheets.

    If a :class:`~django.contrib.flatpages.models.FlatPage` is found for
    this url, it is passed to the template to include in display.
    '''

    fpage = get_flatpage(request)

    # graph of just people directly connected to the belfast group
    if mode == 'egograph':
        js_view = 'network:bg-js'
    elif mode == 'groupsheet-model':
        js_view = 'network:bg-gs-js'
    return render(request, 'network/bg.html',
                  {'bg_uri': BELFAST_GROUP_URI,
                  'js_view': js_view, 'mode': mode, 'flatpage': fpage})


@last_modified(rdf_nx_lastmod)
def group_people_js(request, mode='egograph', output='full'):
    '''Return Belfast Group network graph data as JSON, for use with
    :meth:`group_people`.

    Optionally filter
    the data by minimum degree, if min_degree is specified as a url parameter.
    When generating the node and link data, nodes are annotated with
    degree, in degree, out degree, betweenness centrality, and eigenvector
    centrality if available.  (In/out degree is only available for directed
    graphs.)

    :param mode: egograph: network information for a one- or two-degree
        egograph centered around the Belfast Group; groupsheet-model:
        alternate network graph based on the Group sheets themselves
    :param output: full: node and link data; adjacency: adjacency matrix,
        used for generating chord diagram
    '''

    if mode == 'egograph':
        degree = request.GET.get('degree', 1)
        extra_opts = {}
        try:
            degree = int(degree)
            # currently only support 1 or 2 degree
            degree = max(1, min(degree, 2))
            # NOTE: degree 2 graph is large enough that it *must* be filtered
            # to be sensible and usable on the webpage;
            # by trial & error, I found a minimum degree of 5 to be reasonable
            if degree == 2:
                extra_opts['min_degree'] = 5
        except ValueError:
            # if a value is passed that can't be converted to int, fallback to 1
            degree = 1

        belfast_group = RdfOrganization(network_data().copy(), BELFAST_GROUP_URI)
        graph = belfast_group.ego_graph(radius=degree, types=['Person', 'Organization'],
                                        **extra_opts)

        # annotate nodes in graph with degree
        # FIXME: not a directional graph; in/out degree not available
        graph = annotate_graph(graph,
            fields=['degree', 'in_degree', 'out_degree',
                    'betweenness_centrality',
                    'eigenvector_centrality'])

    elif mode == 'groupsheet-model':
        graph = gexf.read_gexf(settings.GEXF_DATA['bg1'])
        graph = annotate_graph(graph,

belfast/network/templates/network/bg.html
{% extends 'page_base.html' %}
{% load static %}

{% block page-subtitle %} : {{ flatpage.title }}{% endblock %}

{% block head-extras %}
  {{ block.super }}
   {# <link href="{% static 'js/jquery-ui/css/ui-lightness/jquery-ui-1.10.3.custom.min.css' %}" rel="stylesheet" media="screen"/> #}
 <link href="{% static 'js/jquery-ui/css/redmond/jquery-ui.min.css' %}" rel="stylesheet" media="screen"/>
  <script type="text/javascript" src="{% static 'js/jquery-ui/js/jquery-ui-1.10.3.custom.min.js' %}"></script>
{% endblock %}

{% block page-content %}
{% if flatpage %}
  {% include "flatpages/snippets/flatpage_content.html" %}
{% endif %}

{% include 'network/snippets/graph_with_controls.html' %}

  <script src="{% static 'js/d3.min.js' %}" charset="utf-8"></script>
  <link type="text/css" href="{% static 'css/d3.force.css' %}" rel="stylesheet" media="screen"/>
   <script type="text/javascript" src="{% static 'js/d3.force.js' %}"></script>
   <script type="text/javascript">
     ForceGraphControls({
      target: '#graph-controls',
      graph_options: {
        target: "#network-graph",
        url: "{% url js_view %}",
        width: 'auto',
        height: 450,
        highlight: ['{{ bg_uri }}', 'Belfast Group, 1966-1972', 'Belfast Group, 1963-1966'],
        labels: true,
        {% if mode == 'egograph' %}
        degree_toggles: [1, 2],    // enable toggling between one- and two- degree egographs
        {% endif %}
        node_info_url: "{% url 'network:node-info' %}",
        gravity: 0.7,
        link_distance: 75,
        {% if mode == 'groupsheet-model' %}
        link_weight_adjustment: 3,
        {% endif %}
      }
    });
   </script>
{% endblock %}

belfast/network/templates/network/chord.html
{% extends 'page_base.html' %}
{% load static %}

{% block page-subtitle %} : {{ flatpage.title }}{% endblock %}

{% block page-content %}
{% if flatpage %}
  {% include "flatpages/snippets/flatpage_content.html" %}
{% endif %}

{% with min_degree=3 %}
<div class="row">
 <div id="chart" class="col-xs-12 col-sm-8">
  <div class="graph-loading text-center">Loading...</div>
 </div>
{% comment %}
<!-- rotate controls -->
 <div class="controls">
  <ul>
    <li class="rotate-up">
      <a href="#">Up</a>
    </li>
    <li class="rotate-down">
      <a href="#">Down</a>
    </li>
  </ul>
 </div>
{% endcomment %}

 <div id="key" class="col-xs-12 col-sm-4">
 </div>
</div>

  <script src="{% static 'js/d3.min.js' %}" charset="utf-8"></script>
  <link type="text/css" href="{% static 'css/d3.chord.css' %}" rel="stylesheet" media="screen"/>
   <script type="text/javascript" src="{% static 'js/d3.chord.js' %}"></script>
   <script type="text/javascript">
      var options = {
        target: '#chart',
        matrix: "{% url 'network:bg-js-matrix' %}",
        nodes: "{% url 'network:bg-js' %}",
        max_size: 720,
        node_info_url: "{% url 'network:node-info' %}",
      };
      ChordDiagram(options);

      function resize_chorddiagram() {
        console.log('resizing');
        var width = d3.min([options.max_size, parseInt(d3.select(options.target).style('width'), 10)]);
        var current_width = d3.min([options.max_size, parseInt(d3.select(options.target + ' svg').style('width'), 10)]);
        // chord diagram has to be reloaded in order to set size
        // this is expensive, so only resize if we're actually changing width
        if (width != current_width) {
            d3.select(options.target + ' svg').remove();
            $('.graph-loading').show();   // show loading indicator while graph is re-initialized
            ChordDiagram(options);
        }

      }

      d3.select(window).on('resize', resize_chorddiagram);

   </script>

{% endwith %}
{% endblock %}

belfast/network/templates/network/graph.html
{% extends 'page_base.html' %}
{% load static %}

{% block page-subtitle %} : Network Graph{% endblock %}

{% block head-extras %}
  {{ block.super }}
 <link href="{% static 'js/jquery-ui/css/ui-lightness/jquery-ui-1.10.3.custom.min.css' %}" rel="stylesheet" media="screen"/>
  <script type="text/javascript" src="{% static 'js/jquery-ui/js/jquery-ui-1.10.3.custom.min.js' %}"></script>
{% endblock %}

{% block page-content %}
<div>See also:
  <ul>
    <li><a href="{% url 'network:bg' %}">a network graph of people connected to
  the Belfast Group</a></li>
    <li><a href="{% url 'network:bg-gs' %}">alternate model of the Belfast Group network, based on the Group sheets</a></li>
  <li><a href="{% url 'network:chord' %}">a chord diagram of the network</a></li>
  <li><a href="{% url 'network:map' %}">a map of places connected to the network</a></li>
</ul>
</div>

<p>Force-directed network graph people, places, and organizations.
   (Graph is weighted, and nodes of zero-degree have been omitted.)
  Notes are colored by type.
  Mouse over a label to see the text more clearly.</p>

{% include 'network/snippets/graph_with_controls.html' %}

  <script src="{% static 'js/d3.min.js' %}" charset="utf-8"></script>
  <link type="text/css" href="{% static 'css/d3.force.css' %}" rel="stylesheet" media="screen"/>
   <script type="text/javascript" src="{% static 'js/d3.force.js' %}"></script>
   <script type="text/javascript">
      ForceGraphControls({
        target: "#graph-controls",
        graph_options: {
           target: "#network-graph",
              url: "{% url 'network:js' mode='full' %}",
              width: 1000,
              height: 650,
            }
        });
   </script>
{% endblock %}

belfast/network/templates/network/map.html
{% extends 'page_base.html' %}
{% load static %}

{% block page-subtitle %} : {{ flatpage.title }}{% endblock %}

{% block head-extras %}
<script type="text/javascript" src="{% static 'js/jquery.ui.map.full.min.js' %}"></script>
{% endblock %}

{% block page-content %}
{% if flatpage %}
{% include "flatpages/snippets/flatpage_content.html" %}
{% endif %}

<div class="panel panel-default">
  <div class="panel-heading col-xs-12">

    <div class="col-xs-12 col-sm-9">
      <p>A map of all places referenced in our data specific to the Belfast Group and the people associated with it.</p>
    </div>
    <div class="col-xs-12 col-sm-3">
      <!-- Single button -->
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          Filter by person <span class="caret"></span>
        </button>
        <ul class="dropdown-menu map-filter" role="menu">
          {% for id, name in people.iteritems %}
          <li><a id="{{ id }}">{{ name }}</a></li>
          {% endfor %}
          <li class="divider"></li>
          <li class="active"><a id="view_all">View All</a></li>
        </ul>
      </div>
    </div>
  </div>

  {# FIXME: height % seems to be ignored entirely... #}
  <div id="map_canvas" class="panel-body" style="height:90%;min-height:550px;">
    {# <div id="map_canvas" style="border:1px solid black;width:75%;height:80%;position:absolute"> #}
    <br />
  </div>
</div>

<script type="text/javascript" src='https://maps.googleapis.com/maps/api/js?key={{ api_key }}'></script>
<script type="text/javascript">
  function initMap() {

  }

  fetch('{% url '
      network: map - js ' %}')
    .then((response) => {
      return response.json();
    })
    .then((data) => {
      let openWindow = null;
      let iconBase = '{% static '
      img / ' %}map_marker_';
      let bounds = new google.maps.LatLngBounds();
      let map = new google.maps.Map(document.getElementById('map_canvas'), {
        zoom: 4,
        center: {
          lat: 0,
          lng: 0
        },
        disableDefaultUI: true,
        zoomControl: true,
        fullscreenControl: true
      });
      data.markers.forEach(marker => {
        console.log(iconBase, marker.icon);
        let mapMarker = new google.maps.Marker({
          position: {
            lat: parseFloat(marker.latitude),
            lng: parseFloat(marker.longitude)
          },
          map: map,
          title: marker.title,
          icon: `${iconBase}${marker.icon}.png`
        });
        bounds.extend(mapMarker.position);
        marker.mapMarker = mapMarker;

        let infoWindow = new google.maps.InfoWindow({
          content: marker.content
        });
        mapMarker.addListener('click', function () {
          infoWindow.open(map, mapMarker);
          if (openWindow && openWindow != infoWindow) {
            openWindow.close()
          }
          openWindow = infoWindow;
        });
      });
      map.fitBounds(bounds);
      let mapFilter = document.getElementsByClassName('map-filter')[0];
      let links = mapFilter.getElementsByTagName('a');
      for (let link of links) {
        link.addEventListener('click', function (event) {
          for (let link of links) {
            link.parentNode.classList.remove('active');
          }
          link.parentNode.classList.add('active');
          data.markers.forEach(marker => {
            if (event.target.id == 'view_all') {
              marker.mapMarker.setVisible(true);
              event.target.parentNode.classList.add('active');

            } else if (marker.tags.includes(event.target.id)) {
              marker.mapMarker.setVisible(true);
              // event.target.parentNode.classList.add('active');
            } else {
              marker.mapMarker.setVisible(false);
              // event.target.parentNode.classList.remove('active');
            }
          })
        })
      }
    });
</script>
{% endblock %}

belfast/network/templates/network/node_info.html
<div class="node-info-detail"> {# node-info is container element #}
<h4>{% firstof person.fullname node.label %}</h4>

{% if person %}
  {% if person.has_profile %}
    <small><a href="{{ person.identifier }}">[view profile]</a></small>
  {% endif %}

  {% if person.groupsheets %}
  <p>{{ person.groupsheets|length }} groupsheet{{ person.groupsheets|pluralize}}
    <small><a href="{% url 'groupsheets:list' %}?author={{ person.slug }}">[view list]</a></small></p>
  {% endif %}

{% else %}
{# display gexf node information as fallback/ minimum content? #}
{# node stats? degree, connectedness? #}
{% endif %}

{% if poems %}
<p>Mentioned in {% for p in poems %}
 <a href="{{ p.identifier }}">{{ p.title }}</a>{% if not forloop.last %}; {% endif %}{% endfor %}.</p>
{% endif %}
</div>

belfast/network/templates/network/overview.html
{% extends 'page_base.html' %}
{% load static %}

{% block page-subtitle %} : {{ flatpage.title }}{% endblock %}

{% block page-content %}
  <h1 property="schema:name">{{ flatpage.title }}</h1>



<div class="clearfix"></div>

  {# <div class="container-fluid"> #}
  <div id="network-images" class="row">
    <div class="panel col-sm-6 col-md-3 text-center">
      <div class="thumbnail">
          <a href="{% url 'network:bg' %}">
              <img src="{% static 'img/bg-thumb.png' %}" alt="A thumbnail of the network graph of people associated with the Belfast Group."/>
          </a>
          <div class="caption text-left">
              This network graph shows the people directly connected
              to the Belfast Group, as well as the connections between them.
          </div>
      </div>
    </div>

    <div class="panel col-sm-6 col-md-3 text-center">
      <div class="thumbnail">
          <a href="{% url 'network:chord' %}">
              <img src="{% static 'img/chord-thumb.png' %}" alt="A thumbnail of the chord diagram visualization of the people associated with the Belfast Group."/>
          </a>
          <div class="caption text-left">
              This chord diagram makes the connections of an individual associated with
               the Belfast Group easily visible. It uses the same data as the first network graph.
          </div>
      </div>
    </div>

    <div class="panel col-sm-6 col-md-3 text-center">
      <div class="thumbnail">
          <a href="{% url 'network:bg-gs' %}">
              <img src="{% static 'img/bgalt-thumb.png' %}" alt="A thumbnail of the network graph of the two periods of the Belfast Group."/>
          </a>
          <div class="caption text-left">
              This network graph displays the two time periods of the Belfast Group, helping
              visualize who was connected to the Group at certain moments.
          </div>
      </div>
    </div>

    <div class="panel col-sm-6 col-md-3 text-center">
      <div class="thumbnail">
          <a href="{% url 'network:map' %}">
              <img src="{% static 'img/map-thumb.png' %}" alt="A thumbnail of a map visualization of places associated with the Belfast Group"/>
          </a>
          <div class="caption text-left">
              A map of places connected to people associated with the Belfast Group: where
              they lived and worked, as well as places mentioned in their writing.
          </div>
      </div>
    </div>
  </div>

  {% include "flatpages/snippets/flatpage_content.html" %}

{% url 'network:gexf' mode='all' as gexf_url %}
<p>Download our <a href="{{ gexf_url }}">network data as GEXF</a>.</p>


{% endblock %}