belfast/groupsheets/urls.py
from django.conf.urls import patterns, include, url
from belfast.groupsheets import views

urlpatterns = patterns(
    '',
    url(r'^$', views.list_groupsheets, name='list'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<id>[a-z0-9_-]+)/$', views.view_sheet, name='view'),
    url(r'^xml/(?P<name>[-a-z0-9_.]+)/$', views.teixml, name='xml'),
)

belfast/pages/urls.py
from django.conf.urls import patterns, url
from django.contrib.flatpages import views as fpviews


urlpatterns = patterns('',
    url(r'^overview/$', fpviews.flatpage, {'url': '/overview/'},
        name='overview'),
    url(r'^biographies/$', fpviews.flatpage, {'url': '/biographies/'},
        name='bios'),
    url(r'^credits/$', fpviews.flatpage, {'url': '/credits/'},
        name='credits'),
    url(r'^network/about/$', fpviews.flatpage, {'url': '/network/about/'},
        name='network-about'),
    url(r'^essays/$', fpviews.flatpage, {'url': '/essays/'},
        name='essays'),
)

belfast/people/urls.py
from django.conf.urls import patterns, include, url
from belfast.people import views

urlpatterns = patterns('',
    url(r'^$', views.list, name='list'),
    url(r'^(?P<id>[a-z0-9:_-]+)/$', views.profile, name='profile'),
    url(r'^(?P<id>[a-z0-9:_-]+)/ego.json$', views.egograph_js, name='egograph-js'),
    # url(r'^(?P<id>[a-z0-9:_-]+)/ego-graph/$', views.egograph, name='egograph'),
    url(r'^(?P<id>[a-z0-9:_-]+)/ego-graph/node/$', views.egograph_node_info, name='egograph-node'),
)

belfast/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib.sitemaps import FlatPageSitemap

from belfast.pages import views as pages_views
from belfast.sitemaps import OtherViewsSitemap
from belfast.groupsheets.sitemaps import GroupSheetsSitemap, XmlDocumentsSitemap
from belfast.people.sitemaps import ProfileSitemap

# enable django db-admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', pages_views.site_index, name='site-index'),
    url(r'^groupsheets/', include('belfast.groupsheets.urls',
        namespace='groupsheets')),
    url(r'^people/', include('belfast.people.urls',
        namespace='people')),
    url(r'^network/', include('belfast.network.urls',
        namespace='network')),
    url(r'^', include('belfast.pages.urls')),
    # add redirect for favicon at root of site
    (r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True)),
    # Examples:
    # url(r'^$', 'belfast.views.home', name='home'),
    # url(r'^belfast/', include('belfast.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),


    # belfast group rdf ontology
    #   http://belfastgroup.library.emory.edu/ontologies/2013/6/belfastgroup/
    url(r'^ontologies/2013/6/belfastgroup/$',
        TemplateView.as_view(template_name='bg-ontology.xml',
        content_type='text/xml'), name='bg-ontology'),
    url(r'^robots\.txt$',
        TemplateView.as_view(template_name='robots.txt',
        content_type='text/plain'), name='robots.txt'),
)

# xml sitemaps for search-engine discovery
sitemaps = {
    'groupsheets': GroupSheetsSitemap,
    'xmlgroupsheets': XmlDocumentsSitemap,
    'profiles': ProfileSitemap,
    'flatpages': FlatPageSitemap,
    'other': OtherViewsSitemap
}

urlpatterns += patterns('django.contrib.sitemaps.views',
    (r'^sitemap\.xml$', 'index', {'sitemaps': sitemaps}),
    (r'^sitemap-(?P<section>.+)\.xml$', 'sitemap', {'sitemaps': sitemaps}),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/page_base.html
{% extends 'site_base.html' %}

{% block page-subtitle %} : {{ flatpage.title }}{% endblock %}

{% block content %}
<div class="container">
{% block page-content %}
{% endblock %}
</div>
{% endblock %}

templates/site_base.html
{% load static %}
{% comment %}
NOTE: This site uses RDFa and schema.org vocabulary.  Every page will be declared as schema:Webpage
by default; use page_rdf_type to override with a webpage subclass.
{% endcomment %}
<!DOCTYPE html>
<html lang="en" xmlns:schema="http://schema.org/"
{# additional namespaces (primarly for semantic web/RDFa) #}
{% for prefix, ns in extra_ns.iteritems %}xmlns:{{ prefix}}="{{ ns }}" {% endfor %}>
  <head>
    <title>{% block page-title %}Belfast Group Poetry|Networks{% block page-subtitle %}{% endblock %}{% endblock %}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="google-site-verification" content="WWdn3okWneQob5r6S1Svxtf87zwE1FHre0bRMvUzPvQ" />
    {% if debug %}
      <link rel="icon" type="image/ico" href="{% static 'img/favicon-dev.ico' %}" />
    {% else %}
      <link rel="icon" type="image/ico" href="{% static 'img/favicon.ico' %}" />
    {% endif %}

    {# bootstrap v2 #}
    {# <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen"/> #}
    {# <link href="{% static 'bootstrap/css/bootstrap-responsive.min.css' %}" rel="stylesheet" media="screen"/> #}

    {# Bootstrap core CSS #}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    {# Custom CSS for the 'Belfast' Template #}
    <link href="{% static 'css/belfast-style.css' %}" rel="stylesheet" />
    <link href='//fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic' rel='stylesheet' type='text/css'/>

    {# <link href="{% static 'css/local.css' %}" rel="stylesheet" media="screen"/> #}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/belfast.js' %}"></script>

    {% block head-extras %}{% endblock %}
  </head>
  <body typeof="{{ page_rdf_type|default:'schema:Webpage' }}" about="{{ page_rdf_url|default:request.build_absolute_uri }}"
   {% block body-attrs %}{% endblock %}>

 <nav class="navbar navbar-fixed-top navbar-white" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'site-index' %}">Belfast Group Poetry|<i>Networks</i></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">

        <ul class="nav navbar-nav">
          {% url 'overview' as overview_url %}
          <li><a {% if request.path = overview_url %} class="current"{% endif %} href="{{ overview_url }}">Overview</a></li>
          {% url 'groupsheets:list' as groupsheet_list %}
          <li><a {% if request.path = groupsheet_list %} class="current"{% endif %} href="{{ groupsheet_list }}">Group Sheets</a></li>
          {# FIXME: use people list or bios here? #}
          {% url 'people:list' as people_list %}
          <li><a {% if request.path = people_list %} class="current"{% endif %} href="{{ people_list }}">People</a></li>
          {% url 'network:overview' as network_url %}
          <li><a {% if request.path = network_url %} class="current"{% endif %} href="{{ network_url }}">Networks &amp; Maps</a></li>
          {% url 'essays' as essay_url %}
          <li><a {% if request.path = essay_url %} class="current"{% endif %} href="{{ essay_url }}">Essays</a></li>
          {% url 'credits' as credits_url %}
          <li><a {% if request.path = credits_url %} class="current"{% endif %} href="{{ credits_url }}">Credits</a></li>
          {% if user.is_authenticated and user.is_staff %}
          <li><a href="{% url 'admin:index' %}"><span class="glyphicon glyphicon-cog"></span></a></li>
          {% endif %}
          <li class="search">
            <form class="form-search navbar-search pull-right" action="{% url 'groupsheets:search' %}">
              {{ kwsearch_form.keywords }}
              <button type="submit" class="btn btn-search"><span class="glyphicon glyphicon-search"></span></button>
            </form>
          </li>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>

    {# <div class="container"> #}  {# NOTE: every page but index could probably use this #}
      {% block content %}{% endblock %}
    {# </div> #}

  <div class="footer">
    <div class="container">
      <!-- FOOTER -->
      <footer class="row">
        <div class="col-xs-12 col-sm-10">
        <p>
          <a href="http://digitalscholarship.emory.edu/">Emory Center for Digital Scholarship</a>
          <span class="middot">&#xb7;</span> {# middot #}
          <a href="http://marbl.library.emory.edu">Manuscript, Archives, and Rare Books Library</a>
          <span class="middot">&#xb7;</span>
          <a href="http://www.emory.edu/">Emory University</a>
        </p>
        </div>

      <div class="col-xs-12 col-sm-2">
        <div class="lits">
          <p>Powered by:</p>
          <img src="{% static 'img/LITS-logo.png' %}"
            alt="Emory LITS logo"
            title="Emory LITS logo"/>

          <p id="sw_version" class="pull-right">{{ SW_VERSION }}</p>
        </div>

      </div>

      </footer>
      <!-- /END OF FOOTER -->
    </div><!-- /container -->
  </div><!-- /.footer-->

{# TODO: move into a local.js or similar #}
    <script>
    $(function () {
      $('input[name=keywords]').tooltip();
    });
    </script>
{% block endbody %}{% endblock %}


{% if not debug %}   {# google analytics code #}
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-51682905-3', 'auto');
ga('send', 'pageview');

</script>
{% endif %}

</body>

</html>